name: Python Hello World

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # - name: Run Python
      #   run: |
      #     python -c "print('Hello from GitHub Actions!')"

      - name: Show Path
        run: |
          python scripts/check_paths.py